In [1]:
from google.colab import files
uploaded = files.upload()

Saving Iris.csv to Iris.csv


In [2]:
# ===============================
# IMPORTS
# ===============================
import numpy as np
import pandas as pd

# ===============================
# LOAD DATASET
# ===============================
df = pd.read_csv("Iris.csv")   # change name if needed

print("Dataset Preview:")
print(df.head())

# ===============================
# ENCODE LABELS (STRING → NUMBER)
# ===============================
def encode_labels(column):
    unique_vals = list(set(column))
    mapping = {val: i for i, val in enumerate(unique_vals)}
    encoded = np.array([mapping[val] for val in column])
    return encoded, mapping

# ===============================
# NORMALIZE DATA
# ===============================
def normalize(X):
    return (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))

# ===============================
# TRAIN TEST SPLIT
# ===============================
def train_test_split(X, y, test_size=0.2):
    indices = np.arange(len(X))
    np.random.shuffle(indices)

    split = int(len(X) * (1 - test_size))

    return X[indices[:split]], X[indices[split:]], y[indices[:split]], y[indices[split:]]

# ===============================
# DISTANCE FUNCTION
# ===============================
def euclidean_distance(a, b):
    return np.sqrt(np.sum((a - b) ** 2))

# ===============================
# KNN ALGORITHM
# ===============================
def knn_predict(X_train, y_train, X_test, k=3):
    predictions = []

    for test_point in X_test:
        distances = []

        for i in range(len(X_train)):
            dist = euclidean_distance(test_point, X_train[i])
            distances.append((dist, y_train[i]))

        distances.sort(key=lambda x: x[0])
        neighbors = [label for _, label in distances[:k]]

        prediction = max(set(neighbors), key=neighbors.count)
        predictions.append(prediction)

    return np.array(predictions)

# ===============================
# ACCURACY
# ===============================
def accuracy(y_true, y_pred):
    return np.sum(y_true == y_pred) / len(y_true)

# ===============================
# CONFUSION MATRIX
# ===============================
def confusion_matrix(y_true, y_pred):
    classes = np.unique(y_true)
    matrix = np.zeros((len(classes), len(classes)), dtype=int)

    for t, p in zip(y_true, y_pred):
        matrix[t][p] += 1

    return matrix

# ===============================
# PREPARE DATA
# ===============================
X = df.iloc[:, :-1].values   # features
y, label_map = encode_labels(df.iloc[:, -1].values)  # labels

X = normalize(X)

# Split
X_train, X_test, y_train, y_test = train_test_split(X, y)

# ===============================
# TRAIN & TEST
# ===============================
k = 5
y_pred = knn_predict(X_train, y_train, X_test, k)

# ===============================
# RESULTS
# ===============================
print("\nLabel Mapping:", label_map)
print("K:", k)
print("Accuracy:", accuracy(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Dataset Preview:
   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Label Mapping: {'Iris-setosa': 0, 'Iris-virginica': 1, 'Iris-versicolor': 2}
K: 5
Accuracy: 1.0

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
